### ISSUE TITLE
G29 Support

### ISSUE THREAD

**Issue by lichtamberg** [jackhumbert/FreeTheWheel#1]
Could you maybe add support for the Logitech G29? Thanks!

**Comment by jackhumbert** [comment]
Sorry, don't have my iRacing sub anymore, or a G29 :)

**Comment by RajanSathi** [comment]
how do you compile?

**Comment by MarcoBrenn** [comment]
HI Guys, how could i compile the new version with G29 support an MacOS X?

**Comment by RajanSathi** [comment]
Logitech Mac software officially supports the G29 now

Sent from my iPhone

On 20 Dec 2017, at 17:35, MarcoBrenn <notifications@github.com<mailto:notifications@github.com>> wrote:


HI Guys, how could i compile the new version with G29 support an MacOS X?
