### ISSUE TITLE
Logitech G920 Support

### ISSUE THREAD

**Issue by 3tasker1** [jackhumbert/FreeTheWheel#3]
Hi,
I tried this with my logitech G920 but it doesn't find the wheel. Any ideas?

Thanks

Chris

**Comment by 3tasker1** [comment]
This is in the result of ioreg -p IOUSB 

> G920 Driving Force Racing Wheel for Xbox One@14100000  <class AppleUSBDevice, id 0x100000306, registered, matched, active, busy 0 (29 ms), retain 9>

**Comment by RajanSathi** [comment]
Hi,

I can't get this working with either.

Regards

SATHI

On 20 Aug 2016, at 14:04, Chris Tasker <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I tried this with my logitech G920 but it doesn't find the wheel. Any ideas?

Thanks

Chris

-
